### ISSUE TITLE
Missing GitHub labels

### ISSUE THREAD

**Issue by visortelle** [haskellfoundation/volunteering#4]
A regular user can't label issues.

The "GitHub issues templates" feature makes it possible to add a label automatically on issue creation.

But repo admin should add them first.

Labels to create:

```
Project Opportunity
Speaker Available
Volunteer Available
```

[How to create labels docs.](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#creating-a-label)

**Comment by myShoggoth** [comment]
You are absolutely right, I completely forgot to do this step. Fixed, and thank you!
