### ISSUE TITLE
Mentor for beginner Haskeller available

### ISSUE THREAD

**Issue by myShoggoth** [haskellfoundation/volunteering#8]
### Your Name

Andrew Boardman

### Contact Info (optional)

andrew@haskell.foundation

### Areas of Interest

Beginner to intermediate level Haskell

### Commitment (time, frequency, etc.)

One one hour session per month, 30 minutes of code review per week.

**Comment by visortelle** [comment]
I would like to enroll in your magician school 🧙‍♂️.

It would be perfect if we'd choose some problem to solve.
I have a candidate: https://github.com/haskell/haddock/issues/1420

It seems quite long-term and definitely not easy for newcomers like I am, but I have the interest to solve it right now.

Or maybe you have some other more prioritized and/or simpler issue to warm up?

🪄🪄🪄😄

**Comment by myShoggoth** [comment]
Fantastic! And I love the problem, too, that looks great in many ways. 

Email me at andrew@haskell.foundation and we'll coordinate times!

**Comment by E01T** [comment]
Hello Andrew, Is it possible to accept me as a mentee?
I started learning haskell a couple of weeks ago and I am keen to learn more.

kind regards

**Comment by samfrances** [comment]
Hi Andrew. I would definitely be keen to take you up on your mentorship offer. I have worked through "Learn you a Haskell" and have been working through "Haskell Programming from First Principles", but could definitely do with some help and advice getting to the point where I can solve non-exercise problems independently in Haskell.

**Comment by myShoggoth** [comment]
Thank you all for your interest, I've directly contacted two people for mentorship. Hopefully others will make themselves available soon as well, and I'll re-post if I have more availability.
